---

- name: Add Nginx Repository
  apt_repository: repo="ppa:nginx/stable" state=present
  register: ppainstalled

- name: Intall Ngnix
  apt: pkg=nginx state=latest
  when: ppainstalled|success
  notify:
  - Start Nginx

- name: Add h5bp Config
  copy: src=h5bp dest=/etc/nginx/ owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
  - Reload Nginx


- name: Add Site Config
  template: src=site.j2 dest=/etc/nginx/sites-available/site owner=root group=root

- name: Enable Site Config
  file: src=/etc/nginx/sites-available/site dest=/etc/nginx/sites-enabled/site state=link




