---

- name: Add Nginx Repository
  apt_repository: repo="ppa:nginx/stable" state=present
  register: ppainstalled

- name: Intall Ngnix
  apt: pkg=nginx state=latest
  when: ppainstalled|success
  notify:
  - Start Nginx

- name: Add h5bp Config Files
  copy: src=h5bp dest=/etc/nginx/ owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Updated Nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
  notify:
  - Reload Nginx
